global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'receiver'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['receiver:8080']

  - job_name: 'analyzer'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['analyzer:8081']